"""
Archive factory for creating new archives in the Unified Archive Framework.

Provides utilities to bootstrap new archives with proper structure and metadata.
"""

from pathlib import Path
from typing import Optional, Dict, Any
from datetime import datetime

from .base_archive import BaseArchive
from .registry import register_archive


def create_archive(
    name: str,
    root: Path,
    config: Optional[Dict[str, Any]] = None,
    auto_register: bool = True
) -> BaseArchive:
    """
    Create a new archive with proper structure and metadata files.
    
    Creates:
    - Root directory
    - metadata/ and data/ subdirectories
    - README.md (from template)
    - MANIFEST.md (from template)
    - HASH_INDEX.md (from template)
    
    Args:
        name: Name of the archive
        root: Root directory path for the archive
        config: Optional configuration dictionary
        auto_register: Whether to automatically register in registry
        
    Returns:
        Initialized BaseArchive instance
    """
    root = Path(root)
    
    # Create archive instance
    archive = BaseArchive(root=root, name=name, config=config)
    
    # Create directory structure
    archive.ensure_structure()
    
    # Create README.md
    _create_readme(archive)
    
    # Create MANIFEST.md
    _create_manifest(archive)
    
    # Create HASH_INDEX.md
    _create_hash_index(archive)
    
    # Register archive
    if auto_register:
        register_archive(name, root)
    
    return archive


def _create_readme(archive: BaseArchive) -> Path:
    """
    Create README.md from template.
    
    Args:
        archive: BaseArchive instance
        
    Returns:
        Path to created README.md
    """
    template_path = Path(__file__).parent / "archive_templates" / "readme_template.md"
    
    try:
        with open(template_path, "r", encoding="utf-8") as f:
            template = f.read()
    except (OSError, IOError):
        # Fallback template
        template = """# {{archive_name}}

**Created:** {{date}}

## Overview

This archive was created using the Unified Archive Framework (UAF).

## Structure

```
{{archive_name}}/
├── data/           # Archive data files
├── metadata/       # Archive metadata
│   ├── MANIFEST.md
│   └── HASH_INDEX.md
└── README.md       # This file
```

## Usage

Use the UAF tools to manage and validate this archive:

```python
from libs.uaf import BaseArchive, ArchiveValidator, sync_archive

# Load archive
archive = BaseArchive(root="{{archive_root}}", name="{{archive_name}}")

# Validate
validator = ArchiveValidator(archive)
result = validator.validate()
print(result)

# Sync metadata
sync_archive(archive)
```

## Maintenance

- **Last Updated:** {{date}}
- **Format Version:** 1.0
"""
    
    # Replace placeholders
    content = template.replace("{{archive_name}}", archive.name)
    content = content.replace("{{date}}", datetime.now().strftime("%Y-%m-%d"))
    content = content.replace("{{archive_root}}", str(archive.root))
    
    # Write README
    readme_path = archive.root / "README.md"
    with open(readme_path, "w", encoding="utf-8") as f:
        f.write(content)
    
    return readme_path


def _create_manifest(archive: BaseArchive) -> Path:
    """
    Create initial MANIFEST.md from template.
    
    Args:
        archive: BaseArchive instance
        
    Returns:
        Path to created MANIFEST.md
    """
    template_path = Path(__file__).parent / "archive_templates" / "manifest_template.md"
    
    try:
        with open(template_path, "r", encoding="utf-8") as f:
            template = f.read()
    except (OSError, IOError):
        # Fallback template
        template = """# Archive Manifest: {{archive_name}}

**Generated:** {{date}}

## Statistics

- **Total Files:** 0
- **Pdf Files:** 0
- **Csv Files:** 0
- **Image Files:** 0
- **Other Files:** 0
- **Years:** 0

## Files

No files found.

---

*This manifest was automatically generated by the Unified Archive Framework.*
"""
    
    # Replace placeholders
    content = template.replace("{{archive_name}}", archive.name)
    content = content.replace("{{date}}", datetime.now().isoformat())
    content = content.replace("{{file_list}}", "No files found.")
    content = content.replace("{{stats}}", "- **Total Files:** 0")
    
    # Write manifest
    manifest_path = archive.get_manifest_path()
    with open(manifest_path, "w", encoding="utf-8") as f:
        f.write(content)
    
    return manifest_path


def _create_hash_index(archive: BaseArchive) -> Path:
    """
    Create initial HASH_INDEX.md from template.
    
    Args:
        archive: BaseArchive instance
        
    Returns:
        Path to created HASH_INDEX.md
    """
    template_path = Path(__file__).parent / "archive_templates" / "hash_index_template.md"
    
    try:
        with open(template_path, "r", encoding="utf-8") as f:
            template = f.read()
    except (OSError, IOError):
        # Fallback template
        template = """# Hash Index: {{archive_name}}

**Generated:** {{date}}
**Algorithm:** SHA256

## File Hashes

| Hash | File |
| ---- | ---- |

---

*This hash index was automatically generated by the Unified Archive Framework.*
"""
    
    # Replace placeholders
    content = template.replace("{{archive_name}}", archive.name)
    content = content.replace("{{date}}", datetime.now().isoformat())
    content = content.replace("{{algorithm}}", "SHA256")
    content = content.replace("{{hash_list}}", "| Hash | File |\n| ---- | ---- |")
    
    # Write hash index
    hash_index_path = archive.get_hash_index_path()
    with open(hash_index_path, "w", encoding="utf-8") as f:
        f.write(content)
    
    return hash_index_path
